import { Link } from 'react-router-dom';

export function Support() {
  return (
    <div className="min-h-screen bg-[var(--color-bg-primary)] text-[var(--color-text-primary)]">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <div className="mb-8">
          <Link to="/" className="text-sm text-[var(--color-accent)] hover:underline">← Back to Laktic</Link>
        </div>

        <h1 className="font-display text-4xl font-bold mb-2">Support</h1>
        <p className="text-sm text-[var(--color-text-tertiary)] mb-10">Last updated: April 2026</p>

        <div className="space-y-10 text-[var(--color-text-secondary)] leading-relaxed">

          <section>
            <h2 className="font-display text-xl font-bold text-[var(--color-text-primary)] mb-3">Getting Started</h2>
            <p>
              Laktic is an AI coaching platform built for 800m–5K runners. Coaches configure the platform
              with training knowledge and goals; athletes connect their account and receive personalized
              training plans generated and adjusted by their AI coach.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-[var(--color-text-primary)] mb-3">Connecting Strava</h2>
            <ol className="list-decimal pl-5 space-y-2">
              <li>Go to <strong className="text-[var(--color-text-primary)]">Settings → Strava Integration → Connect Strava</strong>.</li>
              <li>Authorize Laktic in the Strava popup that appears.</li>
              <li>Your activities will sync automatically within a few minutes.</li>
            </ol>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-[var(--color-text-primary)] mb-3">Disconnecting Strava</h2>
            <p>
              Go to <strong className="text-[var(--color-text-primary)]">Settings → Strava Integration → Disconnect</strong>.
              All synced activity data is immediately and permanently deleted from Laktic when you disconnect.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-[var(--color-text-primary)] mb-3">Your Training Plan</h2>
            <p>
              Plans are generated by your AI coach based on your fitness level, goal race, and recent activity.
              Your coach can adjust the plan at any time. You can also ask your AI coach to make changes directly
              via the <strong className="text-[var(--color-text-primary)]">Chat</strong> tab.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-[var(--color-text-primary)] mb-3">Account &amp; Data</h2>
            <p>
              You can download all your data or delete your account from{' '}
              <strong className="text-[var(--color-text-primary)]">Settings → Data &amp; Privacy</strong>.
              For privacy questions, see our{' '}
              <Link to="/privacy" className="text-[var(--color-accent)] hover:underline">Privacy Policy</Link>.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-[var(--color-text-primary)] mb-3">Contact Us</h2>
            <p>
              Questions not answered here? Email us at{' '}
              <a href="mailto:support@laktic.com" className="text-[var(--color-accent)] hover:underline">
                support@laktic.com
              </a>
              . We aim to respond within 1 business day.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
